### ISSUE TITLE
workflow schema output doesn't match other things

### ISSUE THREAD

**Issue by wenottingham** [ansible/tower-cli#283]
```
[notting@nostromo: ~]$ tower-cli workflow schema testwf @ymlfu
- job_template: 12
- job_template: 12
- job_template: 13
  success_nodes:
  - failure_nodes:
    - job_template: 14
    job_template: 15
  - failure_nodes:
    - job_template: 14
    job_template: 12
```

**Comment by wenottingham** [comment]
The ask is to have this more like the 'normal' ok/changed/failed output.

**Comment by AlanCoding** [comment]
I struggled getting a grasp on this issue, but I think I we can make something work.

### Status Quo

We simply _don't do human format_ for workflow schema commands. We force-switch the runtime format to JSON. Human format will not work because it expects a resource with columns, and this doesn't fit that pattern.

### Proposal

Printing the "changed" status implies going through the human formatting code. That means that we will need a special clause in the human formatting method to echo the contents in YAML (or in the future, perhaps a fancy graphical view).

Similar to other commands, this _also_ implies that the "changed" key will be present for YAML or JSON output, example:

```yaml
- job_template: 12
- job_template: 12
- job_template: 13
  success_nodes:
  - failure_nodes:
    - job_template: 14
    job_template: 15
  - failure_nodes:
    - job_template: 14
    job_template: 12
- changed: True
```

Of course, the changed status should be smart as to whether any unsafe methods (POST, DELETE, etc.) were used in our new fancy idempotent algorithm.
