### ISSUE TITLE
workflow schema does not replace existing workflow

### ISSUE THREAD

**Issue by wenottingham** [ansible/tower-cli#284]
Maybe I'm misunderstanding, but I have an existing workflow like this:

```
- job_template: 12
- job_template: 12
```

I have a schema file that defines the following structure:

```
- job_template: 13
  success_nodes:
  - failure_nodes:
    - job_template: 14
    job_template: 15
  - failure_nodes:
    - job_template: 14
    job_template: 12
```

I apply it, and I expect it to be as defined in the schema. Instead I get:

```
- job_template: 12
- job_template: 12
- job_template: 13
  success_nodes:
  - failure_nodes:
    - job_template: 14
    job_template: 15
  - failure_nodes:
    - job_template: 14
    job_template: 12
```
