### ISSUE TITLE
Maintain human-readable ordering in workflow schema echo

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-cli#327]
This issue proposes to enforce a standard ordering in the workflow schema output.

Current:

```yaml
- failure_nodes:
  - id: 62
    inventory_source: 40
  - id: 63
    inventory_source: 41
  id: 52
  job_template: 37
```

Proposed:

```yaml
- job_template: 37
  id: 52
  failure_nodes:
  - inventory_source: 40
    id: 62
  - inventory_source: 41
    id: 63
  
```
