### ISSUE TITLE
Inventory variables should appear in JSON format if --format json requested

### ISSUE THREAD

**Issue by mikeycmccarthy** [ansible/tower-cli#331]
Stumbled across this one while looking into a support issue via RedHat support (01894363).

Steps to reproduce:
1. Create an inventory, and add some variables in YAML format
2. Query the inventory via tower-cli and observe the structure of the variables field
3. Go back to the inventory via the UI and hit the json toggle and then save
4. Perform step 2 again and notice the change of format of the variables field

Expected behaviour
I expected that the toggle boxes were just changing a visual representation of the same underlying data. It seems that it is more than that though. Asking for --format json sounds to me like even the inventory variables should be as json.

I'm writing a playbook that can upsert specific variables in an inventory. To do this I need to read the inventory variables in as a variable, with code like this:

```yaml
- hosts: localhost
  tasks:

   - name: Get inventory
     command: tower-cli inventory get 3 --format json
     register: inventory

   - name: Access inventory variable variables
     debug:
       var: ((inventory.stdout|from_json).variables|from_json).fooagain
```

It seems the second from_json will work if the variables are in a json form, otherwise I guess I need from_yaml (I'll test now).

It'd be nice to not need to know how the variables are saved - maybe just my opinion though!
