### ISSUE TITLE
add support for vault_credential in workflow_template schema

### ISSUE THREAD

**Issue by MansM** [ansible/tower-cli#668]
We use a set of workflows in order to paramatize the job_templates
We can add the machine credential, but we cant add the vault credential like this :(

example of what it can look like:
```
- job_template: Group/all-clusters/template/3.11/caas-preinstall
  inventory:  Group/clusterX/inventory/3.11
  vault_credential:  Group/VaultCredentialX
  credential: Group/MachineCredentialX
  success:
  - job_template: Group/all-clusters/template/3.11/install
    inventory:  Group/clusterX/inventory/3.11
    vault_credential:  Group/VaultCredentialX
    credential: Group/MachineCredentialX
    success:
    - job_template: Group/all-clusters/template/3.11/caas-postinstall
      inventory:  Group/clusterX/inventory/3.11
      vault_credential:  Group/VaultCredentialX
      credential: Group/MachineCredentialX
```
