### ISSUE TITLE
job template creation with associated credentials since AWX 5.0

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/tower-cli#719]
I was about to create a bug in AWX until I found [this reply](https://github.com/ansible/awx/issues/4148#issuecomment-504763528) which shows it's expected behavior, but right now the ansible module `tower_job_template`, which in turn uses `tower-cli` as far as I can see, cannot create a job template with credential association anymore (it worked up until including AWX 4.0).

As stated in the linked comment, two requests are necessary, so either `tower-cli` should wrap that or the ansible module should handle this. What is your opinion on this or did I miss some progress in one of the related pieces that would tackle this issue?

There is no error on ansible module execution and the credential name is sent with the request as it used to. The job template gets created, however, it is not associated with any credentials.

**Comment by tumbl3w33d** [comment]
cc @wwitzel3 as maintainer of the ansible module

**Comment by AlanCoding** [comment]
I don't think it would be prudent to get rid of this field, because we still have to support old versions.

https://github.com/ansible/tower-cli/blob/7b7d3a8cc991e1c4fb4cb5bc4e4c1f251f52daa0/tower_cli/resources/job_template.py#L44

But maybe some post-creation or post-modification checking that all fields have been set might help people out. But ultimately it's the modules that need to change in some way or another.

**Comment by Klaas-** [comment]
@AlanCoding I think he means tower-cli no longer creates job_templates with credentials:

`tower-cli job_template create --name tower-cli-test --project my_project --playbook my_playbook.yml --credential my_credential --inventory my_inventory`

will come back as a success but will not have a credential associated.

**Comment by AlanCoding** [comment]
This situation is the same for both --credential and --vault-credential.

**Comment by Klaas-** [comment]
didn't recognize that, sorry. I was just puzzled why you talk about vault_credentials :)

**Comment by Klaas-** [comment]
For anyone else stumbling over this issue - as a workaround I now use rest_get and uri modules (https://github.com/redhat-cop/infra-ansible/blob/master/roles/ansible/tower/library/rest_get.py)

My workflow looks like this:
rest_get credentials, look up credential id, rest_get credentials of template, check if ssh credential already associated, remove if wrong credential, add credential unless right one already defined

**Comment by adpavlov** [comment]
> For anyone else stumbling over this issue - as a workaround I now use rest_get and uri modules (https://github.com/redhat-cop/infra-ansible/blob/master/roles/ansible/tower/library/rest_get.py)
> 
> My workflow looks like this:
> rest_get credentials, look up credential id, rest_get credentials of template, check if ssh credential already associated, remove if wrong credential, add credential unless right one already defined

Could you please share your playbook for this?

**Comment by Klaas-** [comment]
> 
> 
> > For anyone else stumbling over this issue - as a workaround I now use rest_get and uri modules (https://github.com/redhat-cop/infra-ansible/blob/master/roles/ansible/tower/library/rest_get.py)
> > My workflow looks like this:
> > rest_get credentials, look up credential id, rest_get credentials of template, check if ssh credential already associated, remove if wrong credential, add credential unless right one already defined
> 
> Could you please share your playbook for this?

I can't share my whole role because it's very specific to my usecase but in general I built it like https://github.com/redhat-cop/infra-ansible/tree/master/roles/ansible/tower

```
- name: Remove associated machine credentials if they don't match the defined ones
  uri:
    url: "{{ tower_uri }}/api/v2/job_templates/{{ tower_created_job_template.id }}/credentials/"
    headers:
       Authorization: Bearer {{ tower_cli_token }}
    method: POST
    status_code: 204
    body_format: json
    body: '{ "id": {{ tower_job_template_credential_already_associated_ssh.id }},"disassociate":true }'
  changed_when: yes
  when: tower_job_template_credential_already_associated_ssh is defined and (tower_job_template_credential_to_associate.name != tower_job_template_credential_already_associated_ssh.name) # noqa 204

- name: Associate right ssh credential
  uri:
    url: "{{ tower_uri }}/api/v2/job_templates/{{ tower_created_job_template.id }}/credentials/"
    headers:
       Authorization: Bearer {{ tower_cli_token }}
    method: POST
    status_code: 204
    body_format: json
    body: '{ "id": {{ tower_job_template_credential_to_associate.id }} }'
  changed_when: yes
  when: tower_job_template_credential_already_associated_ssh is undefined or tower_job_template_credential_to_associate.name != tower_job_template_credential_already_associated_ssh.name # noqa 204
```
