### ISSUE TITLE
workflow schema cannot create a workflow of workflows

### ISSUE THREAD

**Issue by itcultus** [ansible/tower-cli#737]
I have a few workflows that I want to combine in one. 
Currently, from the GUI I can do it. 
However, tower-cli throws an error when I upload the schema. 

```
tower-cli workflow schema test @./schema.yml 
Error: The requested object could not be found.
```

The schema is: 

```yaml
- project: prj_myproject
  success:
  - job_template: first_workflow
    success:
      - job_template: second_workflow

```
When I create it from the GUI I have no issues. If I replace the workflows with Job Templates, it works just fine.

**Comment by AlanCoding** [comment]
I expect that the specification would follow the syntax of

```yaml
- project: prj_myproject
  success:
  - workflow: first_workflow
    success:
      - workflow: second_workflow
```

This is because "workflow" is a separate template type from "job template".
